apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firefly-iii.fullname" . }}
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "firefly-iii.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "firefly-iii.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "firefly-iii.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.existingSecret }}
                  name: {{ .Values.secrets.existingSecret -}}
                  {{ else }}
                  name: {{ include "firefly-iii.fullname" . }}
                  {{- end }}
                  key: app-key
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.existingSecret }}
                  name: {{ .Values.secrets.existingSecret -}}
                  {{ else }}
                  name: {{ include "firefly-iii.fullname" . }}
                  {{- end }}
                  key: db-database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.existingSecret }}
                  name: {{ .Values.secrets.existingSecret -}}
                  {{ else }}
                  name: {{ include "firefly-iii.fullname" . }}
                  {{- end }}
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.existingSecret }}
                  name: {{ .Values.secrets.existingSecret -}}
                  {{ else }}
                  name: {{ include "firefly-iii.fullname" . }}
                  {{- end }}
                  key: db-password
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
