{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . }}
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
data:
  {{- if .Values.secrets.appKey }}
  app-key: {{ .Values.secrets.appKey | b64enc | quote }}
  {{- else }}
  app-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  db-database: {{ .Values.secrets.dbDatabase | b64enc | quote }}
  db-username: {{ .Values.secrets.dbUsername | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
{{- end}}
